### ISSUE TITLE
 plugin unsupported: com.sharinglabs.datepicker 

### ISSUE THREAD

**Issue by steven-fernandez** [Sharinglabs/cordova-plugin-datepicker#15]
I'm getting:  plugin unsupported: com.sharinglabs.datepicker on phonegap build

**Comment by Heshyo** [comment]
What's the cli version you're using, how do you reference the plugin in `config.xml`, and did it stop working recently?

**Comment by steven-fernandez** [comment]
I'm using cli-5.2.0.  About the referencing...I followed the readme. 
Added:
<feature name="DatePicker">
    <param name="ios-package" value="DatePicker"/>
</feature>

<feature name="DatePickerPlugin">
    <param name="android-package" value="com.sharinglabs.cordova.plugin.datepicker.DatePickerPlugin"/>
</feature>

and 

<gap:plugin name="com.sharinglabs.cordova.plugin.datepicker" />

That's it...any ideas?

**Comment by Heshyo** [comment]
I think the 1st part (with the `feature`) is not needed (I don't have it anymore in my `config.xml`).

You can try using
`<plugin name="com.sharinglabs.cordova.plugin.datepicker" source="pgb" spec="1.1.3" />`
for the 2nd part. That's how PGB shows it to me in the `Plugins` tab.

I know PGB is now pushing people to use either npm or straight github instead of having plugins on PGB. See http://phonegap.com/blog/2016/02/16/git-plugins/ on how to point to git directly (I haven't tested it though).

**Comment by steven-fernandez** [comment]
Thanks for your help :)

**Comment by Heshyo** [comment]
Does that mean it's working fine for you now? If so, what did you end up using?

**Comment by steven-fernandez** [comment]
I've ended up not using an datepicker but will get back to it for the next app update and use yours...I'll update you when I do this... thanks :)
